### ISSUE TITLE
Map is not compatible with this version

### ISSUE THREAD

**Issue by Starcommander** [junjunguo/PocketMaps#139]
As documented in #138 in this case the map compatiblity check fails.
It is only possible to open the map the first time.
Afterwards the message "not compatible" appears instead.

**Comment by Scafir** [comment]
I quickly mentionned in #137 (probably not very helpful, but at least it's now in the right place)

> killing the app while the map is still loading does some strange things. I will have "Map is not compatible with this version" and the Downloads folder selected as the destination folder when I launch it again. I then need to wait some time, kill the app, open it again to go back to nominal behaviour.

**Comment by Starcommander** [comment]
@surferjoeit 

Thanks for your information, and testing regarding #138 .
I have created a new pre-release.
Maybe you can test the new apk:
https://github.com/junjunguo/PocketMaps/releases/tag/3.4-pre1
(Installing the apk may clear all settigs and maps of pocketmaps)

Thanks, and best regards,
Paul

**Comment by surferjoeit** [comment]
Many thanks for your support, now it seems that the issue is solved.
All the best
Francesco

**Comment by Starcommander** [comment]
Solved in V3.4

**Comment by Kovaelin** [comment]
I got this message when removing the map and downloading it again. I also noticed that removed maps don't actually remove the downloaded file.

**Comment by Starcommander** [comment]
@Kovaelin 
What is the version of your pocketmaps?
As already mentioned, this issue should be solved in V3.4
Unfortunately the version is still not updated on f-droid, but should be soon.

**Comment by Kovaelin** [comment]
@Starcommander Ah, I see. I had just installed v3.3, and I didn't notice that F-Droid was behind on the update. Thanks.

It's good to have this option on old devices.

**Comment by Starcommander** [comment]
Finally should be fixed now.
